### ISSUE TITLE
Input does not run properly on Windows Seq instances

### ISSUE THREAD

**Issue by Hinni** [Hinni/Seq.Input.AzureEventHub#3]
**Version detail**
OS: **Windows 10 Version 1809 (Build 17763.379)**
Seq Server: **5.1.3000-pre**
Seq.Input.AzureEventHub: **1.0.1**
Seq.Apps: **5.1.0**
Microsoft.Azure.EventHubs.Processor: **3.0.0**

**Description**
Azure Event Hub processor don't work properly on Windows Seq under Seq.Apps.GenericHost.exe. Connections to Event Hub are established successful, but processor falls into timeout. This behaviour is different to Seq docker 5.1.3000-pre where same code works like a charm.
Running test project in Visual Studio 2017 without GenericHost.exe on same Windows machine or with Seqcli 5.1.213 with `app run`  is working, too.

**Screenshot**
![image](https://user-images.githubusercontent.com/3010444/54878818-03c3b680-4e32-11e9-983c-b33c9312f6c5.png)
![image](https://user-images.githubusercontent.com/3010444/54878756-581a6680-4e31-11e9-9088-ac05b7b69d14.png)

**Comment by Hinni** [comment]
Hi @nblumhardt,
I re-tested the app against the latest preview versions of Seq on Windows and Docker. The bug under Windows is in the latest version.
Do you have a GenericHost playground where I could test in detail what the problem is under Windows?
Thanks for your help.

**Comment by nblumhardt** [comment]
Hi @Hinni!

You can start the generic host on the command line on Windows (it's in C:\ProgramFiles\Seq\AppHost) by setting some environment variables and providing some info about the app.

E.g.:

```
# Folder that contains the Seq.Input.AzureEventHub publish output
cd bin/netstandard2.0/publish

# The app host needs this
$env:SEQ_INSTANCE_BASEURI="http://seq.example.com"

# One for each setting to provide to the app
$env:SEQ_APP_SETTING_EVENTHUBCONNECTIONSTRING="some connection string"

# Specify main app type name
& 'C:\Program Files\Seq\AppHost\Seq.Apps.GenericHost.exe' Seq.Input.AzureEventHub.AzureEventHubInput
```

(It's possible to set the working directory, arguments, and environment variables in the Properties > Debug section of the project in Visual Studio so that you can F5 debug it.)

Hope this helps,
Nick

**Comment by Hinni** [comment]
Hi @nblumhardt 

I found the problem. Azure Event Hub has different dlls for 4.6.1 full framework. Within a Seq.Apps.GenericHost.exe it only works with this version. I tried to create a nuget packagge with net462 and netstandard2.0 support. But Seq.Apps.GenericHost.exe always load the netstandard2.0 dlls by default - if there are more supported frameworks.

Is there a flag or something for the generic host to force "old" full framework assembly loading?

Thanks for your Feedback.
Michael

**Comment by nblumhardt** [comment]
Hey @Hinni! I think this lines up with some issues I've been investigating; we've found that, in the current previews, some DLLs were missing that prevented .NET Standard DLLs from loading properly. With the fix in, .NET Standard DLLs should work properly in the app host.

I'll send you a link to the fixed (RC) installer, in case you're able to try it out. Cheers!

**Comment by Hinni** [comment]
Hi @nblumhardt 
I tried it with 5.1.3000 ... on docker it works. On Windows still the same problem.
Interestingly, it runs with seqcli 5.1.213 with `app run` on Windows without any problems.

**Comment by nblumhardt** [comment]
Interesting! I think the common factor is that `seqcli` is running on .NET Core 2.2, while the Seq Windows app host is running on the full framework. (The plan currently is for 6.0 to be Core by default, for apps.)

Wondering if making this package `netstandard`-only might solve it? I'm currently on vacation so just skimming :-) - if there hasn't been a breakthrough I'll get set up in Azure and dig in properly when I'm back next week.

**Comment by Hinni** [comment]
In combination with `Seq-2024.2.11282.msi` on Windows 11 and `datalust/seq:2024.2.11282` on Docker, version 2.0.0 of `Seq.Input.AzureEventHub` works like a charm on both platforms.
