### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by TysonMN** [Hinni/Seq.Input.AzureEventHub#5]
Hello.  I just found this project via [this link](https://github.com/datalust/seq-tickets/discussions/1547#discussioncomment-2541696).  I am interested using this.

I see the last commit was in 2019.  Does that mean that the status of this project is something like "no longer active"?

**Comment by Hinni** [comment]
Hi @TysonMN 

Probably no major adjustments are needed to bring the project up to date if you host Seq in a container.
Do you use a Seq hosted on Windows?

Kind regards
Michael

**Comment by nblumhardt** [comment]
Hi @Hinni, I hope all's well with you!

I had a shot at updating this project to use current versions of its dependencies, include some development-time niceties, and run on all Seq supported platforms. One of our (Seq) customers has tested this out in a non-production environment and reports that it's working for them.

My fork is https://github.com/nblumhardt/seq-input-azure-eventhub; I'm happy getting those changes into a PR back to this repository, or if you're no longer actively maintaining it, I am happy maintaining the fork separately. Open to all ideas - let me know what you think :-)

Best regards,
Nick

**Comment by Hinni** [comment]
Hi @nblumhardt,

Great news 🚀  Thanks for contacting me about this topic. Yes, let's update this repository with your PR. I would like to reactivate this Seq input. I would like to test this then on my environment as well.

Best regards,
Michael

**Comment by nblumhardt** [comment]
Excellent! I'll do that - thanks Michael.

Best regards,
Nick

**Comment by Hinni** [comment]
Hi @TysonMN 

With @nblumhardt contribution of current Seq version know how I was able to push a new major release.

Best regards,
Michael
